# Generated by Django 3.1.7 on 2021-03-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='desk',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
    ]
