# Generated by Django 3.1.7 on 2021-03-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_auto_20210316_1552'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contributor',
            name='unique_user',
        ),
    ]
